#include<stdio.h>
int main()
{
    printf("Stack segment :Contains stack data\nThe stack is used for managing function calls and local variables. It's a LIFO (Last In, First Out) data structure.\n");
    printf("When a function is called, its local variables and some control data (like return addresses) are stored in the stackAfter the function ends, this memory is freed automatically.\nCharacteristics:\nSize: Limited in size and usually much smaller than the heap.\nEfficiency: Fast memory access.\nLifecycle: Memory is managed automatically; you don’t need to manually allocate or free memory.\nScope: Variables are limited to the function they are defined in.");

    printf("\n\n");
    printf("Heap segment :Contains heap data\nThe heap is used for dynamic memory allocation. It's larger than the stack and used for storing data that needs to persist or grow dynamically during a program's execution.\nMemory is manually allocated and deallocated using functions like malloc/free in C or new/delete in C++.\nObjects that need to live beyond the scope of the function that created them (like dynamically-sized arrays or structures) are stored here.\nSize: Typically much larger than the stack.\nEfficiency: Slower memory access than the stack due to the need to manage allocation and deallocation.\nLifecycle: The programmer must manually allocate and free memory to avoid memory leaks.");

    printf("\n\n");
    printf("BSS segment (Block Started by Symbol) :Contains variables that are declared globally or statically but are not explicitly initialized by the programmer.\nThese variables are automatically initialized to zero by the system when the program starts.");

    printf("Since the BSS segment only holds uninitialized variables, it doesn’t take up any actual space in the compiled executable file.\nIt just indicates that a certain amount of memory should be allocated for these variables when the program is loaded.\n");
    printf("\n\n");
    printf("Data segment :Contains variables(global & static) that have been explicitly initialized in the source code.\nThe data segment is typically divided into two sections:\nRead-Only Data Segment and Read-Write Data Segment\n");
    printf("\n\n");
    printf("Code segment :Contains the machine code generated by the compiler or assembler.\nThese instructions are executed by the CPU when the program runs.");
}
